name: Lint

on:
  # Trigger the workflow on all pull requests, and pushes to main
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Get file changes
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '

      - name: Echo file changes
        run: |
          echo Changed files: ${{ steps.get_file_changes.outputs.files_modified }} ${{steps.get_file_changes.outputs.files_added}}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_args: ${{ steps.get_file_changes.outputs.files_modified }} ${{steps.get_file_changes.outputs.files_added}}
